
export default {
    production: 'cr-production',
    vilo: 'https://static.crunchyroll.com/vilos',
    client_id: 'gewoo3hubkzp0evqszbd',
    client_secret: 'K3aSb9s_LYeq9WPEAHfmGqS70nIICTY-',
    client_id_sso: 'ltccxd10yl6cqcn1acx1',
    url: 'https://www.crunchyroll.com',
    beta_url: 'https://beta-api.crunchyroll.com',
    sso_url: 'https://sso.crunchyroll.com',
    url_static: 'https://static.crunchyroll.com',
    url_drm: 'https://cr-play-service.prd.crunchyrollsvc.com',
    url_pl: 'https://pl.crunchyroll.com',
    url_license: 'https://cr-license-proxy.prd.crunchyrollsvc.com',
    accounting_id: 'crunchyroll',
    cast_id: '4D84B31C',
    url_eec: 'https://eec.crunchyroll.com',
    app_config: 'app-config-default-production.json',
    version_name: '3.70.4',
    app_id: 'cr-android',
    os_release_version: '13',
    content_types: ['series', 'movie_listing', 'episode'],
    sortByValues: ['popularity', 'newly_added', 'alphabetical'],
    ratingContentTypes: ['1s', '2s', '3s', '4s', '5s'],
    ratingEpisodeTypes: ['up', 'down'],
}
