
export default {
    production: 'cr-production',
    vilo: 'https://static.crunchyroll.com/vilos',
    clientId: 'xunihvedbt3mbisuhevt',
    clientSecret: '1kIS5dyTvjE0_rqaA3YeAh0bUXUmxW11',
    clientIdSso: 'ltccxd10yl6cqcn1acx1',
    url: 'https://www.crunchyroll.com',
    urlBeta: 'https://beta-api.crunchyroll.com',
    urlSso: 'https://sso.crunchyroll.com',
    urlStatic: 'https://static.crunchyroll.com',
    urlDrm: 'https://cr-play-service.prd.crunchyrollsvc.com',
    urlPl: 'https://pl.crunchyroll.com',
    urlLicense: 'https://cr-license-proxy.prd.crunchyrollsvc.com',
    accountingId: 'crunchyroll',
    castId: '4D84B31C',
    urlEec: 'https://eec.crunchyroll.com',
    appConfig: 'app-config-default-production.json',
    versionName: '3.89.2',
    appId: 'cr-android',
    osReleaseVersion: '13',
    contentTypes: ['series', 'movie_listing', 'episode'],
    sortByValues: ['popularity', 'newly_added', 'alphabetical'],
    ratingContentTypes: ['1s', '2s', '3s', '4s', '5s'],
    ratingEpisodeTypes: ['up', 'down'],
}
